version: '3'

services:
  ticket-calendar:
    container_name: 12306ticket
    build: .
    ports:
      - "2306:2306"
    volumes:
      - ./ics:/app/ics
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    restart: always
